### ISSUE TITLE
bug - hides disappearing

### ISSUE THREAD

**Issue by tirzah2** [OhhLoz/Harvester#1]
Hi!
love your module!
after i harves a creature, for example a boar, it put a tusk and a hide in the inventory. but i noticed that the hide is not actually real because i cant delete it (gives error) and if i refresh the page it disappears. the tusk stays. 
![image](https://github.com/OhhLoz/Harvester/assets/83312683/28dde901-d803-471c-9e99-b095ce312ddb)

**Comment by OhhLoz** [comment]
Hi, Sorry I should have put how the module works on the module page & thank you for using it. 
When harvesting, it prompts the user to roll a skill check (based on the type of creature) and based on the roll result gives the components. 
For example, when harvesting the Boar you stated it asks for a Nature Roll and has the following:
- DC 5: Boar Tusks
- DC 10: Boar Hide
It also seems to be conflicting with Beavers crafting module / system interface

**Comment by tirzah2** [comment]
Hi.. yes that's correct. it give the boar tusk and the boar hide, but the boar hide disappears if i refresh the page (F5)

**Comment by OhhLoz** [comment]
Sorry I misunderstood, Are you harvesting with a Player Character Actor? 
Is the tickbox "Link Actor Data" ticked in the token configuration?
That's strange behaviour I havent come across

**Comment by tirzah2** [comment]
hi.
yes, bot the player and the boar are linked actors.
![image](https://github.com/OhhLoz/Harvester/assets/83312683/9439d72c-3c43-413a-af6c-e9c7ac055abf)
this is the error that comes out when i try to delete the hide. like if it doesnt exist. and infact, when i refresh the page, it disappears from the inventory.
![image](https://github.com/OhhLoz/Harvester/assets/83312683/444fbb70-ba64-4007-8453-0b3882caddda)

**Comment by OhhLoz** [comment]
I can't seem to be able to replicate the issue, the best I can assume is that it could be a mod conflict. 
Are you using Forge? I have no access to Forge so I haven't tested it using Forge.

**Comment by tirzah2** [comment]
Hi, no, i have it on uber space..
but the strange thing is that it happens only on hides.. not on tusks or other kind of items..

**Comment by OhhLoz** [comment]
Not sure why that would happen especially as it's retrieved the correct item. When it gets added to the Actor the Foundry API automatically calls an update on the actor to ensure its added correctly,

**Comment by tirzah2** [comment]
Yes I am, latest.

**Comment by OhhLoz** [comment]
> Yes I am, latest.

Ah I built it on 10.291 so perhaps v11 breaks some things, I was avoiding updating as I was running a campaign but now its finished I can update my Foundry and the module to v11, provided thats the issue

**Comment by tirzah2** [comment]
i can also confirm that is not just the hides... its like when its more than 1 item, then some of them are broken, and 1 is not.
i tried with basilisk, the teeth were fine, the rest disappeared at refresh.
now the only way to make it work is to not auto assign harvest, and drag and drop it from the chat. not a biggy.

**Comment by OhhLoz** [comment]
v1.4.0 works with Foundry V11 now and hopefully this error wont return anytime soon!
