### ISSUE TITLE
v11 Broken

### ISSUE THREAD

**Issue by Thorin48** [OhhLoz/Harvester#13]
I don't know if this has been updated for v11 but when i try to import the roll tables and other things there's nothing inside the folders. I can post a screenshot of what it looks like if needed.

**Comment by OhhLoz** [comment]
Hi, Thats weird,
I just did a full reinstall of the module and everything is imported correctly for me.
What Foundry version and module version are you on? 1.6.5 should work for all V11 versions. Did you download it through the foundry app?

**Comment by Thorin48** [comment]
Foundry is v.11 build 308
Module Version 1.6.5
and ive done both install on foundry and install using the direct link

**Comment by Thorin48** [comment]
![image](https://github.com/OhhLoz/Harvester/assets/56743592/b607c821-fa85-4ac6-94cf-834d88072651)
 Here's a image of the compendium when I first open the module.

**Comment by OhhLoz** [comment]
If you navigate to `C:\Users\Loz\AppData\Local\FoundryVTT\Data\modules\harvester\packs` and open the harvest.db in a text editor is it empty? The only thing I can think of is that the migration from .db to foundry v11 failed for some reason. You could try deleting the harvest folder within that directory if harvest.db is not empty to try to force it to reimport the database.

**Comment by Thorin48** [comment]
Its all there which is super weird. Ill delete the whole thing and retry

**Comment by Thorin48** [comment]
Still no files ive deleted and redownloaded  I'm at a loss of what is happening

**Comment by OhhLoz** [comment]
I've no idea either, you could try using my files to see if that works
[packs.zip](https://github.com/OhhLoz/Harvester/files/12562632/packs.zip)

**Comment by Thorin48** [comment]
Worth a try

**Comment by Thorin48** [comment]
you know that worked I don't know how but it worked

**Comment by Thorin48** [comment]
Sorry to bug you about that but that was weird

**Comment by OhhLoz** [comment]
No worries thats what this place isfor, I'm glad it fixed it.
Its a weird bug though, hopefully it doesn't come up too often
