### ISSUE TITLE
Harvester Question

### ISSUE THREAD

**Issue by Thorin48** [OhhLoz/Harvester#14]
This is a question I couldn't really find a question tab on github so I put it here sorry in advance.

I'm trying to set up for my players to harvest boars every time I've clicked harvest it says please select only one token when I only have one token selected. I'm kinda lost at what to do here and I've tried looking thru the internet but I cant find a discord, wiki, or video explaining it. 
I have a boar in the custom folder and the actor folder they are identical with the features having nature and the inventory of the boar having the same thing.

**Comment by OhhLoz** [comment]
Hi, 
It should say only target one token, the module uses the target to harvest so the controller of the actor needs to have the thing it wants harvesting targeted for the module to work correctly. It limits it to 1 for ease.

**Comment by Thorin48** [comment]
When they target the creature it just puts the harvest feature into chat they can't interact with anything else. I feel like I haven't done the setup correctly
![image](https://github.com/OhhLoz/Harvester/assets/56743592/8432e922-99e9-4f64-9e1f-d2c9d10824f8)

**Comment by OhhLoz** [comment]
Please can you send a screenshot of the sheet you made inside the Custom compendium? Even if it can't find an entry it should put a message in chat saying that nothing is valuable can be found on the corpse
