### ISSUE TITLE
Using a randomized token name breaks the Harvest action

### ISSUE THREAD

**Issue by damien-jeanmaire** [OhhLoz/Harvester#15]
When using something that randomizes the name of a token (by adding an adjective, or a number to it), whether with the prototype token options, or via a module like Token Mold, the Harvest action stops working.
This is because the name used to retrieve the harvest result is the randomized token name, instead of the original token name.

An easy way to circumvent that would be to use the name of the prototype token instead.

**Comment by OhhLoz** [comment]
It's supposed to use the Actor name rather than the Token name which I didn't seem to implement for the Harvest action yet did for the Loot action.
