### ISSUE TITLE
Issue - All compendiums empty (V11.308) 

### ISSUE THREAD

**Issue by UmbraZeal** [OhhLoz/Harvester#16]
Hey, really love the idea of this mod but sadly no matter what I do all the compendiums are empty, the actions, harvest, and loot roll table compendiums are empty (I assume the custom ones should be empty).

I have tried this on my main world and a fresh test world with only this mod and the required socketlib mod.

**Comment by OhhLoz** [comment]
Hi, none of them should be empty. Someone else had a similar issue, I believe its an issue with Foundry Migrating the .db files they used in V10 to the new database format they use in V11.
[database_converted.zip](https://github.com/OhhLoz/Harvester/files/12651221/database_converted.zip)
You can try extracting that zip inside your module folder, it should be in AppData\Local\FoundryVTT\Data\modules\harvester

**Comment by UmbraZeal** [comment]
Perfect that's fixed it, ty very much!
