### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by RubberDuckieGod** [OhhLoz/Harvester#17]
I have installed it on Forge VTT and when I get into game it does not have the tables or modules populated. Is there something else I need to do?
![Slide1](https://github.com/OhhLoz/Harvester/assets/92833545/4f5f1447-545e-44db-951c-f40f0b7ca0fc)

**Comment by OhhLoz** [comment]
Hi, none of them should be empty. Someone else had a similar issue, I believe its an issue with Foundry Migrating the .db files they used in V10 to the new database format they use in V11.
[database_converted.zip](https://github.com/OhhLoz/Harvester/files/12651221/database_converted.zip)
You can try extracting that zip inside your module folder, it should be in AppData\Local\FoundryVTT\Data\modules\harvester

**Comment by RubberDuckieGod** [comment]
Then what to do?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OhhLoz** [comment]
I told you what to do

**Comment by RubberDuckieGod** [comment]
Figure it out thank you.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by RubberDuckieGod** [comment]
I tried installing but its still not populating

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OhhLoz** [comment]
Try reinstalling and extracting the zip before opening a world. Normally extracting the zip works

**Comment by RubberDuckieGod** [comment]
I have gotten to work in foundry actual but not on forge. Are you aware of any fixes for forge?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by OhhLoz** [comment]
Unfortunately not, I've never used forge so I have no way of testing. I'll try to see if theres a way to handle the migration so it doesn't rely on Foundry migrating the .db itself as it fails every now and then
