### ISSUE TITLE
[Feature request] Customize DC and Skill choice

### ISSUE THREAD

**Issue by RavenknightDM** [OhhLoz/Harvester#2]
Hiya!
I don't understand how the DC for different harvests work. But I wonder if it would be possible to modify the DC values somewhat? Also, the ability to chose what skill is rolled for different harvests would be fantastic.
Either way, thanks a bunch! It's a great module.
/Ravenknight

**Comment by OhhLoz** [comment]
Hi, the DCs & Skill checks are hardcoded when I created the compendium and are included in metadata of each item that cant be seen by the user.
Hopefully in the future I can add a way for users to create custom harvest tables with their own items, at the moment that would require almost a complete rewrite, which is ok however im currently focusing on updating the module to work with v11.

**Comment by OhhLoz** [comment]
This is present in the newest update v1.5.0 for foundry v11, I will add a backwards compatible version for foundry v10 however as persistent storage is not in v10 it will take a bit longer and will perhaps be clunkier.
