### ISSUE TITLE
Feature Request : Add otpion for Harvesting non-dead tokens.

### ISSUE THREAD

**Issue by mcmackj** [OhhLoz/Harvester#21]
First off love the mod. It has replaced several cobbled together functionalities with one defined option and it is appreciated. On to the meat.

I was wondering if it would be possible to give an option to harvest or loot an non-dead token. Figuring this could be flag based and settable within the token configuration window. This would expand the capabilities to loot/harvest items like chest or berry bushes for example. You can do this now, but I presume many of us use a "Death" Icon or Overlay on tokens and having this appear on lootable/harvestable items would not be ideal and may tip off players to functionality the DM may wish for them to discover in other ways.

edit: On further thought this may also expand the capability to add Pick Pocketing in the future.

**Comment by OhhLoz** [comment]
This should be possible now using this setting 
![image](https://github.com/OhhLoz/Harvester/assets/22823143/5db5a047-a739-4aa8-b60f-59ac0df24051)
Although I gather you're saying you have other modules that display an overlay on the character whether or not they have the Dead efffect or not? Yeah it should be easy to add that option

**Comment by mcmackj** [comment]
I was so deep in monkeying around I completely overlooked that setting. My apologies. Added the code to the items to also have the option to turn the body into an ItemPile on Loot. Your use of hook for this was inspired.
