### ISSUE TITLE
Compatibility with Ready Set Roll for D&D 5e

### ISSUE THREAD

**Issue by 59thCaboose** [OhhLoz/Harvester#22]
Hey, I was wondering if it was possible to have compatability with the module Ready Set Roll's Quick Roll feature? The module allows for dice rolls to be done automatically when activating an item, feature, skill, etc, however when this option is enabled, Harvester seems to be unable to register the related harvest roll. 

The first image is what is shown when Quick Roll for Items is enabled, which has no dice result, or option to roll a skill check. 
![Harvest 1](https://github.com/OhhLoz/Harvester/assets/95092139/d0ad6464-7b1b-4261-94a1-248f8942356e)

The second image shows with the feature turned off, and the module works as normal. 
![Harvest 2](https://github.com/OhhLoz/Harvester/assets/95092139/fe1adc64-cec7-42ae-8e81-c9b0dd2645bd)

I don't know if this is technically a Harvester or Ready Set Roll issue, but it would be good fun to get these modules working together for my games. For general info this has been tested on the latest Foundry Version 11 (11.313), with both modules up to date. The console shows no errors, or even anything out of the ordinary.

Obviously this isn't a major issue at all, but anything is appreciated, thank you!

**Comment by OhhLoz** [comment]
Hmm, the Ready Set Rolls code seems rather complex compared to mine. Im assuming it can roll things in Formula / Other Formula which is what Harvester uses. It renames the Other Formula button to the relevant skill check by editing the HTML directly which might be what is messing with Ready Set Roll as it may be looking for "Other Formula" and getting "Nature Skill Check" instead

**Comment by p4535992** [comment]
It should be already solved with the requestor integration.
