### ISSUE TITLE
[FEATURE REQUEST] Wildcards in BRT tables

### ISSUE THREAD

**Issue by ctbritt** [OhhLoz/Harvester#27]
Not sure if this is for you or @p4535992, but it would be great, when using the BRT-Harvest tables, to have wildcards. I've got a number of, for example, zombie variants, and instead of a separate roll table for Feral Zombie, Fungal Spore Zombie, Zombie Wolf, and Zombie -- which all harvest the same thing -- the harvest function could just look for "Zombie" in the source name and apply the general Zombie BRT Table. 

I'll also file this on @p4535992's repo. 

Thanks!

**Comment by OhhLoz** [comment]
Should be fixed in 1.8.0 release
