### ISSUE TITLE
bug - multiple effects given on one harvest action

### ISSUE THREAD

**Issue by OhhLoz** [OhhLoz/Harvester#3]

**Comment by OhhLoz** [comment]
This occurred in a game hosted by a friend, when another user harvested it gave the effect even after it was present on the target. I haven't been able to reproduce it myself

**Comment by justinthejaguar** [comment]
I am experiencing this as well.

**Comment by OhhLoz** [comment]
> I am experiencing this as well.

What version are you running? I've updated quite a lot recently.
I can only imagine multiple users are running the executeAsGM() to add the effect to the token and bypassing the validation checks however that shouldn't be possible.

**Comment by justinthejaguar** [comment]
I am running your latest version last night. To be fair, I’m running a lot of automation modules m, so it’s possible that DAE, MIDI-QOL, or Convenient Effects are reapplying it. I show two effects when I update for loot or harvest. One is a 6 second effect and the other is unlimited. I will grab screenshots and errors (if they’re are any) after work today.

**Comment by OhhLoz** [comment]
Hopefully this should be fixed in versions 1.5.1 for Foundry v11 and 1.3.6 for Foundry v10.

The temporary effect included in the compendium was set to 1 round duration (aka 6 seconds) so it can be safely assumed it was automatically being added by MidiQOL or similar automation.

The problem with this fix is that it won't change already assigned actions on actors, so the effects will still be on the Harvest/Loot actions already present on Actors and will need removing manually.

I'll close this issue for now as I believe its resolved, thank you for your help @justinthejaguar
