### ISSUE TITLE
[Feature Request] Full Skill Item Roll Option

### ISSUE THREAD

**Issue by Nightpresider** [OhhLoz/Harvester#31]
looking for a tweek to this module, by adding a check box in the settings for "Full Skill Item Roll"
Rather than - to my understanding...
module currently gives players a feature called harvest, which checks on canvas target for 0 hp = continue 
Next it prompts player to choose a skill roll (or) auto rolls skill defined in the features of that creature for one named "anyskill" such as Nature, or Survival.
Lastly it looks at the items on that character sheet checking each items Source input field for a number, if that number is =/< than the roll it moves the items to player character sheet.
![image](https://github.com/OhhLoz/Harvester/assets/118228745/9d2797f0-3669-442d-bdc0-cd878f0d4c35)

Change
Do not look on creature's feature for a skill but instead goes straight to the items source and looks for abbreviated skill+# separated by "," so that a player may choose any skill to roll when harvesting and it will check that creatures items for a corresponding DC to that skill.
![image](https://github.com/OhhLoz/Harvester/assets/118228745/67b1c165-c268-4768-a79a-e5bead3dda4a)

Also to be noted
Foundry 5e D&D Items Sourse input box has undergone a change 
![image](https://github.com/OhhLoz/Harvester/assets/118228745/db802e59-dde1-49cd-85b4-b07af15e3571)
i believe you could implement "Full Skill Item Roll" without impacting the original system, by having the code first check for X field of the new Source for "Nat20","Arc10" exc exc  - if blank go back to existing code.

Compatibility
[Poll Request Update settings.js and module.js to integrate Item Piles #29]
- If [Full Skill Item Roll] + [Integrate Item Piles] is completed you will not just have harvesting creatures anymore, you will have filled a large void within foundry for Searching areas, containers, looting in general.

-I too would find this preferrable as I'm sure many within Item-piles vast user base would.

**Comment by Nightpresider** [comment]
@sailbot393 if this were to happen would it be difficult to make compatible with Lock&key
Lock&key set actor difficulty (most likely 1-15) and then Harvest can add to the set difficulty number before results are displayed to players.

**Comment by Saibot393** [comment]
I will look into it

**Comment by OhhLoz** [comment]
Should be fixed in 1.8.0 release
