### ISSUE TITLE
D&D 3.0.x compatibility. 

### ISSUE THREAD

**Issue by ctbritt** [OhhLoz/Harvester#34]
Would request this be updated for dn5e 3.0.x... so far, it runs, without errors, but the button to make a skill check doesn't show up, possibly because of the new D&D chat cards.

**Comment by ctbritt** [comment]
Apologies... looks like there might be a MidiQOL interaction as well. It's looking to replace `<div class="chat-buttons">` but that doesn't exist with midi enabled. What gets generated is `<div class="chat-buttons midi-buttons">`

Here's a screenshot of the section of code in question
![CleanShot 2024-02-22 at 12 26 35](https://github.com/OhhLoz/Harvester/assets/4516034/8db20fe5-a992-42b5-8977-56442faa23b8)

not quite sure how to fix this, as Midi under 3.0 makes some serious changes to the chat card. 

Mind you, it doesn't show the button even when Harvester is the only module enabled, either, so ...

**Comment by OhhLoz** [comment]
Yeah thanks for the issue, as p4535992 mentioned merging the pull request will likely fix the button issue as the current method is rather hacky. Afaik midiqol currently doesnt work with dnd3.0

**Comment by ctbritt** [comment]
Turns out it's not midi -- i'm running the 11.4.x beta. The button vanishes when only Harvester, libwrapper and socketlib are enabled.

**Comment by OhhLoz** [comment]
Fixed as of 1.7.2
