### ISSUE TITLE
Cant loot consumables when harvesting a creature

### ISSUE THREAD

**Issue by Asiermd** [OhhLoz/Harvester#35]
**Module Version:** v1.7.2

**Describe the bug**

**To Reproduce**
1. Create a custom table with items as consumables
2. Try to harvest those consumables
3. See error

**Expected behavior**
For the consumables to be looted as normal

**Screenshots**

![image](https://github.com/OhhLoz/Harvester/assets/45450286/049f1ae3-d7e1-4a3f-bd91-3e67c8713905)

**Browser:**
Google Chrome Versión 122.0.6261.70 (Build oficial) (64 bits)

**Foundry Version:** 

Version 11 Build 315

**Game System:** 

DnD 5e

**Comment by p4535992** [comment]
Ty for ticket we will solve the warning .
Did you have other modules active like Item Piles or BRT ?

**Comment by Asiermd** [comment]
I have (probably too) many, including those 2, i will share screenshots of the one im using right now.
![image](https://github.com/OhhLoz/Harvester/assets/45450286/4614fc38-3bb3-4eb0-b60d-e0e3d05f907e)
![image](https://github.com/OhhLoz/Harvester/assets/45450286/ab5fe008-b2f6-42fb-a216-ff4d181191cb)
![image](https://github.com/OhhLoz/Harvester/assets/45450286/60407a9a-29f5-4fe1-b494-d5224f14e60e)

**Comment by OhhLoz** [comment]
Should be fixed in 1.7.3

**Comment by Asiermd** [comment]
Im sorry, but i dont see it fixed, i try to loot consumables and i cant, im in the 2.4.1 DnD version, havent upgraded it to 3.x.x yet, that may be the problem?

**Comment by OhhLoz** [comment]
> Im sorry, but i dont see it fixed, i try to loot consumables and i cant, im in the 2.4.1 DnD version, havent upgraded it to 3.x.x yet, that may be the problem?

It's possible, 1.7.2 onwards have been made with 3.0.0 in mind. I haven't tested back compatibility. I didn't make the bugfix so I can't say with much certainty.

**Comment by p4535992** [comment]
it should work on 2.4.1. You still say "Loot consumables", did you mean "Harvesting cosumable" ? The loot operation let you only retrieve currency no ?

**Comment by Asiermd** [comment]
I meant harvesting yes, i think im doing everything alright cause i can harvest items categorized as "loot" but not the ones that are "consumables", there is no error in the console either when i try with the minimum modules possible, (harvester, better roll tables and dependencies) so i dont know why can it be.

**Comment by p4535992** [comment]
Can you enable the "debug" settings of the module and see what the logs tell you ?

**Comment by Asiermd** [comment]
![image](https://github.com/OhhLoz/Harvester/assets/45450286/5a7a0e6e-c9ff-4e33-a541-5a0fb2463ed8)

**Comment by p4535992** [comment]
I add a bucnh of logs on 1.7.4, but from the screenshot i can see the source reference is wrong.

Likw i said in the README

In the BRT Harvest Rolltable sheet, the "Source Reference" field is the one used by this module to connect the monster to the rolltable! So **"Source Reference" === "Name of The Monster"** so for example if the monster name is "Ice Wolf" you must put on the source reference "Ice Wolf"

**Comment by Asiermd** [comment]
![image](https://github.com/OhhLoz/Harvester/assets/45450286/06844d89-a114-447f-b002-383baefce101)
![image](https://github.com/OhhLoz/Harvester/assets/45450286/c67dd896-7626-4b5c-b734-ad2b44ea4838)
I used "Harvest" cause its my testing world, so most things have obvious names to why they were created, like the name for the harvesting to be "loot" and "consumable", in this case, the actor being named "harvest"

**Comment by p4535992** [comment]
From the logs everything seem fine , in this case is working right ? we need just to remove the filter for the "loot" type ?

**Comment by Asiermd** [comment]
Im sorry to be annoying, but i wanna know if this will be worked on, if not, i will edit the consumable items that i have.

**Comment by p4535992** [comment]
i'll try to find some time tomorrow

**Comment by Asiermd** [comment]
Thanks a lot.

**Comment by p4535992** [comment]
Try out 1.7.9
