### ISSUE TITLE
[BUG] Every corpse coming up empty regardless of skill roll

### ISSUE THREAD

**Issue by ctbritt** [OhhLoz/Harvester#37]
**Module Version:** v1.7.3

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

No errors show up with debug on.

**Describe the bug**
no matter what I roll on the skill check, it says "After examing the corpse, you realize there is nothing you can harvest"
**To Reproduce**

1. target a dead token
2. Click on Harvest
3. Roll skill check prompted by Requestor

**Expected behavior**
That items would be generated from the Better Roll Table of harvest items, added to the ItemPiles of the dead creature and be able to be harvested

**Screenshots**
![CleanShot 2024-03-03 at 14 28 04](https://github.com/OhhLoz/Harvester/assets/4516034/f0eccbf5-cf2d-4370-9505-f44d6712cfaf)

**Browser:**
- Chromium Engine Version 122.0.6261.94

**Foundry Version:** 
- v11.315

**Game System:** 
- D&D5e 3.0.3

**Additional context**
Have tried with both BRT and without BRT. Same result. Have also tried with only Harvester and Requestor enabled. Same result.

**Comment by p4535992** [comment]
Add on version 1.7.4 a bunch of logs can you tell me what did you see on the web console with the prefix `harvester |` Remember you enable the debug options of the module.

**Comment by ctbritt** [comment]
ok. here's some new data. Only modules active are:
libwrapper
socketlib
Harvester
Better Tables
Requestor
ItemPiles

This is the error I'm getting when I click harvest on a dragon corpse: 
![CleanShot 2024-03-06 at 16 59 54](https://github.com/OhhLoz/Harvester/assets/4516034/415f103b-5bf1-45d5-9a39-ba217a920602)

**Comment by p4535992** [comment]
> ok. here's some new data. Only modules active are: libwrapper socketlib Harvester Better Tables Requestor ItemPiles
> 
> This is the error I'm getting when I click harvest on a dragon corpse: ![CleanShot 2024-03-06 at 16 59 54](https://private-user-images.githubusercontent.com/4516034/310677422-415f103b-5bf1-45d5-9a39-ba217a920602.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjM2NTksIm5iZiI6MTcwOTc2MzM1OSwicGF0aCI6Ii80NTE2MDM0LzMxMDY3NzQyMi00MTVmMTAzYi01YmYxLTQ1ZDUtOWEzOS1iYTIxN2E5MjA2MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMjIxNTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDU3ZjI1MTgxZjg0YzgzOGVjNjhlZDMyNzBmYjIzZDA0YzQ0ZGI0MzJjZGUzZjU5NjMzODMyMTg1NGU2ZjkzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.a9xxoYQ3pB5US3767Tl878EksOQfe5mCi3ILRjpq0Po)

Totally missed that. Fixed on 1.7.6

**Comment by ctbritt** [comment]
if I turn ON `Automatically Assign Items` this is the result: 
![CleanShot 2024-03-06 at 17 15 40](https://github.com/OhhLoz/Harvester/assets/4516034/3c4bd6ed-17f1-450b-9c96-bf9437594b7d)
and console output is this: 
![CleanShot 2024-03-06 at 17 16 01](https://github.com/OhhLoz/Harvester/assets/4516034/67562e8c-1e65-4ea5-aa22-1a909a61c1ef)

The item is added to his inventory automatically, when it should be added to the item pile.

**Comment by ctbritt** [comment]
also, is it normal to have both a pop up and a chat card prompt?

**Comment by ctbritt** [comment]
sorry to be a bother. Now this error with 1.7.6: 
![CleanShot 2024-03-06 at 17 21 49](https://github.com/OhhLoz/Harvester/assets/4516034/7b83a309-2464-4c0a-adbc-0d6359a8682e)

**Comment by p4535992** [comment]
I think this is a new feature "The item is added to his inventory automatically, when it should be added to the item pile.", becuase i think you want:

1) Harvest the target
2) Automatically convert the targeted token to a item piles (with the option to remove all the already present items porblaby...) 
3) Let the players checkout the corpe as a standard item piles

**Comment by p4535992** [comment]
> sorry to be a bother. Now this error with 1.7.6: ![CleanShot 2024-03-06 at 17 21 49](https://private-user-images.githubusercontent.com/4516034/310682602-7b83a309-2464-4c0a-adbc-0d6359a8682e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NjQxNzcsIm5iZiI6MTcwOTc2Mzg3NywicGF0aCI6Ii80NTE2MDM0LzMxMDY4MjYwMi03YjgzYTMwOS0yNDY0LTRjMGEtYWRiYy0wZDYzNTlhODY4MmUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDZUMjIyNDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Nzk3YmVmN2FkZjE1MGJlYTA5OTliMDk4MjE3NzE5Yjk5MmZkNGI2NDgwNTczYjgzYTFkNzgzNzhiMzIzZGIyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.faat0IVmykKRboexQy933XhIzyK0GFTYED40dZ5g3gk)

Fix again on 1.7.7 ....

**Comment by p4535992** [comment]
> also, is it normal to have both a pop up and a chat card prompt?

Is a requestor settings i can probably add module setting for  have only the chat button by default

**Comment by p4535992** [comment]
> also, is it normal to have both a pop up and a chat card prompt?

add a module setting for this on 1.7.8 (by default is false)

**Comment by ctbritt** [comment]
> I think this is a new feature "The item is added to his inventory automatically, when it should be added to the item pile.", becuase i think you want:
> 
> 1. Harvest the target
> 2. Automatically convert the targeted token to a item piles (with the option to remove all the already present items problaby...)
> 3. Let the players checkout the corpe as a standard item piles
> 
> I purposely avoided the second step because without clever filters on targeting, people would destroy their characters because they were wrongly targeting

I think this could skip the conversion to itempiles step. Monk's Token Bar already converts dead tokens to itempiles when combat ends, so maybe you just add a check? That's what I did in my initial PR that added itempiles to the module. 

1. Check the corpse
2. Itempiles? Skip to step 4
3. No itempiles? Convert to itempiles
4. Harvest

**Comment by OhhLoz** [comment]
Should be fixed in 1.8.0 release
