### ISSUE TITLE
[BUG] Unknown Error in Console when pressing button in chat

### ISSUE THREAD

**Issue by Randomisation** [OhhLoz/Harvester#41]
**Module Version:** v1.7.9

![image](https://github.com/OhhLoz/Harvester/assets/77389343/2f4f54d5-b262-41fc-925f-67aaecb5b168)

**Describe the bug**
When attempting to harvest, the button in the chat generates the above error. It does not roll any skill check or roll on loot table. 

**To Reproduce**
1. Select 'dead' token, hit the Harvest feature 
2. Click the "Attempting to Harvest" button in chat
3. See error

**Expected behavior**
Expect when pressing the "Attempting to Harvest" button to roll skill check, generate loot and automatically add to inventory. Having not used this module before, I am not 100% sure how it is meant to work.

**Screenshots**
N/A

**Browser:**
 Firefox (Latest). Also not working directly in Foundry.

**Foundry Version:** v11 Build 315

**Game System:** D&D 5e: v3.1.1

**Comment by p4535992** [comment]
What midi-qol version are you using ?

**Comment by Randomisation** [comment]
Midi QOL version is 11.4.18.1

**Comment by Randomisation** [comment]
Ha! Yes he did indeed! Thanks for taking time out to help and for your work creating these awesome modules! :)
