### ISSUE TITLE
[BUG] Looting Action

### ISSUE THREAD

**Issue by jknolte** [OhhLoz/Harvester#46]
All my PC actors have the Loot action available, even with the Looting action setting disabled:
![image](https://github.com/OhhLoz/Harvester/assets/159180002/9cdec62e-c98a-4eec-8f6f-78588d1f3857)

**Comment by p4535992** [comment]
Should be fixed on 1.8.6 . Sorry you must delete the item manually on preExistent actors.
If you need a macro i can create one just not now
