### ISSUE TITLE
[BUG] Error from Manifest URL

### ISSUE THREAD

**Issue by mbrueckl** [OhhLoz/Harvester#48]
Manifest URL copied into Foundry results in the following error messages:

![Capture](https://github.com/OhhLoz/Harvester/assets/55034615/7cd12a04-969d-4fd5-908e-05dbb1a4c768)

**Module Version:** Unknown - copying this Manifest URL: https://raw.githubusercontent.com/OhhLoz/Harvester/master/src/module.json

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

[localhost-1713903442692.log](https://github.com/OhhLoz/Harvester/files/15082483/localhost-1713903442692.log)

**Describe the bug**
Module fails to install when manifest URL is copied into manifest URL bar, install module screen.

**To Reproduce**
1. Go to 'Install Module' screen in Foundry
2. Paste provided manifest URL into lower bar
3. Click install

**Expected behavior**
Module installs (and makes me happy)

**Browser:**
 - Chrome

**Foundry Version:** 
V11 Build 315
**Game System:** 
D&D 5e

**Comment by p4535992** [comment]
Fixed ty for point that out
