### ISSUE TITLE
 [BUG] Plugin hooks unsupported 11.2.3 12+

### ISSUE THREAD

**Issue by hyrapower** [OhhLoz/Harvester#51]
**Module Version:** v1.8.6
Foundry v11 Build 315
Foundry v12 Build Any

logs attached
[harvesting1.log](https://github.com/user-attachments/files/15571504/harvesting1.log)

Error: Workflow Harvest ZkcQCPBVlIIjgq29 hook preambleComplete deprecated use prePreambleComplete instead
Deprecated since Version 11.2.5
Backwards-compatible support will be removed in Version 12

**Describe the bug**
Functionality around harvesting stops when a player attempts to roll.

**To Reproduce**
1. Select a player character and stand next to a downed, harvestable entity
2. hover over a downed character and hit 't' to target
3. select 'harvest' as an action
4. both pop up, and chat version say 'harvest with 'nat''
5. clicking 'harvest' will trigger the error in the console
6. no feedback from UI and no further code is executed.

**Expected behavior**
I am able to harvest and get the results

**Screenshots**
error screenshot attached.
![image](https://github.com/OhhLoz/Harvester/assets/4219273/ddf600eb-7d02-432a-9738-ed564cf481d9)

**Browser:**
 - Brave

**Foundry Version:** 
Foundry 11 Build 315
Foundry 12 Build Any

**Game System:** 
DnD5E

**Additional context**
Add any other context (like other modules installed) about the problem here.

This used to work until I upgraded to the last stable build of 11. Doesn't work at all for Foundry 12.

**Comment by hyrapower** [comment]
I found that I was able to isolate it as working as designed during testing with only your plugin on. There's something else causing this behavior. Please close this ticket.

**Comment by p4535992** [comment]
The error say ChatMessageMidi maybe is some compatibility issue with Midi-Qol
