### ISSUE TITLE
Custom Loot Sheets

### ISSUE THREAD

**Issue by justinthejaguar** [OhhLoz/Harvester#6]
How do I do it?

I thought perhaps just creating a loot sheet (I duplicated Drow) with the name of the monster might do it, but that appears incorrect.

**Comment by OhhLoz** [comment]
All custom harvest tables for Foundry V11 must be in the "Custom" compendium via the Toggle Edit Lock option.

It should be in the same format as the template included in the "Custom" compendium.
It needs the Actor name to be what you wished looked up, then a feature that is named the skill check.
![image](https://github.com/OhhLoz/Harvester/assets/22823143/d8abd235-0173-4008-b0a1-ff8301128778)
Then it uses each item in its inventory as a harvest drop, the only essential bit being the "DC X" part, replacing that with the DC you wish (the word DC is optional)

If its not recognised when you add it and Harvest then try refreshing, it should already refresh itself.

**Comment by justinthejaguar** [comment]
Ah, so can I only set up the harvest tables, and not loot?

Will this reset on update though since it is in the module compendium?

**Comment by OhhLoz** [comment]
You can setup custom Loot tables inside the Loot compendium however that will be reset on updates.
The Custom compendium won't be overwritten by updates as its a persistent storage compendium.
I can almost certainly add the same mechanic for Loot tables, however, it will mean alot of compendium clutter.

**Comment by justinthejaguar** [comment]
"The Custom compendium won't be overwritten by updates as its a persistent storage compendium.
I can almost certainly add the same mechanic for Loot tables, however, it will mean alot of compendium clutter."

That would be awesome, you're module is certainly not the one that I would blame for too many compendiums. Luckily compendium folders are core now haha. So the loot table only really needs the name of the actor and placed in the existing compendium for now?

**Comment by OhhLoz** [comment]
More or less, it should look similar to below, it doesn't have to be a d100.
The description is for the "Loot All Creatures" setting, if it has "true" then it is a typical creature that could reasonably have loot on it, otherwise it should be "false"
![image](https://github.com/OhhLoz/Harvester/assets/22823143/58d4f0f7-f3ce-43da-8b16-3ba17dc72c3f)
It is in a strange format as it was originally going to be displayed in the chat and the user could click on each currency to roll it themselves however it was quite messy.
So [[/r **ROLLDICE**]]{**CURRENCY**}

**Comment by OhhLoz** [comment]
I added this in the newest version just out, 1.6.2
You should see a new compendium called "Custom Loot" that won't be affected by updates that you can put custom rolltables in for looting currency.

**Comment by OhhLoz** [comment]
Nevermind there's an issue with 1.6.2

**Comment by JackaldaJester** [comment]
Will there only ever be the option to roll for currency? Would it be possible to roll on a table with trinkets?

**Comment by OhhLoz** [comment]
> Will there only ever be the option to roll for currency? Would it be possible to roll on a table with trinkets?

I didn't add the item transfer as other modules do this, hence why I added the option to completely disable the Loot action as the main focus of the module was on the Harvesting. 

I could add it in the future but its not currently planned.

**Comment by JackaldaJester** [comment]
> 
> I didn't add the item transfer as other modules do this, hence why I added the option to completely disable the Loot action as the main focus of the module was on the Harvesting.
> 
> I could add it in the future but its not currently planned.

That actually makes complete sense and something I just overlooked. Thanks for your hard work, and I look forward to using this module.

**Comment by p4535992** [comment]
Other module do this kinda of job we just let the player retrieve item from a actor.
Item piles is been massive integrate recently and is good enough for all the use case.
