### ISSUE TITLE
updated for V11 build 306?

### ISSUE THREAD

**Issue by SecretSquirrel77** [OhhLoz/Harvester#8]
![image](https://github.com/OhhLoz/Harvester/assets/77705375/6ad3c957-60cf-4250-b4b7-794b9ccb4837)

Can't seem to install on the latest Version.

**Comment by OhhLoz** [comment]
Ah thats because I set a maximum of the tested version, I didn't realise it would prevent downloads I thought it would say it was made for an older version.
