### ISSUE TITLE
Sanitize actors when loot is not needed

### ISSUE THREAD

**Issue by BrotherSharper** [OhhLoz/Harvester#9]
I was fumbling around on how to get the module working and I turn on to have the "loot" action enabled for all actors. Now that I figured out that the module adds new actions to actors, I want to get rid of the "loot" action on all the NPC actors that it was added to.

It would be amazing if the module could sanitize itself if the action is not needed anymore.

**Comment by OhhLoz** [comment]
That's a good idea, I'll likely add it in a future update

**Comment by OhhLoz** [comment]
Apologies its so delayed however this is now present in v1.6.5 and v1.3.9.
Thank you for the suggestion.
